# Generated by Django 4.2.7 on 2025-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("vendor", "Vendor"),
                    ("customer", "Customer"),
                ],
                max_length=10,
            ),
        ),
    ]
