# Generated by Django 4.2.7 on 2025-08-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("vendor", "Vendor"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
